title: "My Math Blog"
description: "Rigorous math writing and daily posts"
baseurl: "" # leave empty for root site
url: "https://GitDisciplined.github.io"

theme: jekyll-theme-cayman # a nice-looking theme with sidebar support

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
