title: "My Math Diary"
description: "An attempt to learn the art and beauty of mathematics"
baseurl: "" # leave empty for root site
url: "https://GitDisciplined.github.io"
paginate: 5 # Optional: controls number of posts per page

theme: jekyll-theme-cayman # a nice-looking theme with sidebar support

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
